name: Build .NET Framework

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0

      - name: Restore NuGet packages
        run: nuget restore novideo_srgb.sln

      - name: Build solution
        run: msbuild novideo_srgb.sln /p:Configuration=Release

      - name: Prepare output folder
        run: |
          mkdir output
          copy novideo_srgb\bin\x64\Release\*.exe output\
          copy novideo_srgb\bin\x64\Release\*.dll output\
          copy unlock_registry\unlock_registry.bat output\
          copy LICENSE output\
          copy LICENSE-THIRD-PARTY output\

      # Upload the output folder as artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: output/
